### ISSUE TITLE
When changing viz view the visualisation stays the same 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/covid19-tracker#10]
![Screenshot 2020-06-18 at 08 52 01](https://user-images.githubusercontent.com/3273659/84993321-0c905e80-b141-11ea-823f-c53b38433617.png)
![Screenshot 2020-06-18 at 08 52 09](https://user-images.githubusercontent.com/3273659/84993324-0d28f500-b141-11ea-8b77-9b9665c585fb.png)

**Comment by drkane** [comment]
This is now fixed - plus it's sped up a bit so it doesn't look as slow...
