### ISSUE TITLE
Set date parameters for COVID19-tracker

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/covid19-tracker#2]
Based on inquiries from publishers we are likely to start seeing existing grants with significant variations due to the crisis tagged with COVID19 appearing in 360 data this week.
To avoid confusion we should set an earliest award date for the data used in the site. Currently the earliest award is 2020-03-17 so could start with that and amend if necessary.

**Comment by drkane** [comment]
Good idea @KDuerden . At the moment it's any grant after 2020-01-01 ([from here](https://github.com/ThreeSixtyGiving/covid19-tracker/blob/master/360covid-tracker/fetch_data.py#L17)), this could be easily changed.

It would be good if we were somehow able to distinguish between amendments to existing grants and new grants, and track them both.
