### ISSUE TITLE
List all the search words used to identify COVID19 grants

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/covid19-tracker#4]
For clarity for users and also this will help publisher support if there are issues with data intended to be included which doesn't conform. 
This could be included in next gen coronavirus tracker - although it would be useful to have the search terms listed here for reference.

**Comment by drkane** [comment]
Good idea. For reference, the code used to find that grants is here:

https://github.com/ThreeSixtyGiving/covid19-tracker/blob/a3c3ad0fda2aeb9bac88a0e6466182599aafcd12/covidtracker/fetch_data.py#L20-L28
