### ISSUE TITLE
Rename community foundation group filter to avoid confusion

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/covid19-tracker#40]
UK Community Foundations the organisation has published grants data: https://covidtracker.threesixtygiving.org/funder/GB-CHC-1004630

This leads to potential confusion because the filter grouping of all CFs who have published is also called UK Community Foundations: https://covidtracker.threesixtygiving.org/funder/community-foundations

![image](https://user-images.githubusercontent.com/20462640/170653716-ab4d414b-c3f7-48af-818b-a5d438ab4346.png)

Rename the grouping to avoid confusion. 

I suggest something like 'Community foundation grants' - there are probably better ideas though!

**Comment by drkane** [comment]
Ah yes, that's not ideal.

Changing it is easy, and we can keep the existing URL so any links will still work.
