### ISSUE TITLE
Issue with filter when publishing funder is also grant recipient

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/covid19-tracker#8]
Oxfordshire CF has published 78 covid grants which appear in the tracker. However the filtered view also includes the grant awarded by Indigo Trust to OCF, and the results show 2 funders: 
https://covidtracker.threesixtygiving.org/funder/GB-CHC-1151621

**Comment by drkane** [comment]
I've removed this in 0e0670ea0134092bd28d9f67b1b4fc66963fcfd0 - it now only shows grants where the selected funder is the funder.
